name: classy_crafth_app
description: ClassyCrafth Flutter App

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  image_picker: ^1.0.7
  http: ^1.2.0
  razorpay_flutter: ^1.3.7
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.4.0

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon.png"

flutter_native_splash:
  color: "#E46B2D"
  image: assets/splash.png
  android: true
  ios: true

flutter:
  uses-material-design: true

  assets:
    - assets/products/
    - assets/icon.png
    - assets/splash.png

